=== Piotr-Piwoni/Piotr-Piwoni.github.io/projectMetadata.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ProjectMetadata",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "short": {
      "type": "string"
    },
    "long": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cover": {
      "type": "string"
    },
    "outLinks": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "name",
          "url"
        ]
      }
    },
    "additionalAssets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "downloadFiles": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "page": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "short",
    "tags",
    "cover",
    "page"
  ]
}

=== Piotr-Piwoni/Piotr-Piwoni.github.io/projects/John/metadata.json
{
  "name": "John",
  "short": "A Narrative driven, point-and-click game set in Scotland during the 70's.",
  "tags": [
    "Team",
    "School",
    "Unity",
    "2D",
    "Game",
    "C#",
    "PC",
    "Shader"
  ],
  "outLinks": [
    {
      "name": "Itch",
      "url": "https://gluetrap-games.itch.io/john"
    }
  ],
  "cover": "images/cover.png",
  "additionalAssets": [
    "images/a1.png",
    "images/a2.png",
    "images/a3.png",
    "images/a4.png",
    "images/a5.png"
  ],
  "downloadFiles": [
    "files/John.zip"
  ],
  "page": "index.html"
}

=== Piotr-Piwoni/Piotr-Piwoni.github.io/projects/CMP301-Graphics/metadata.json
{
  "name": "DX11 Shader Scene",
  "short": "A project showing my shader work using DirectX 11.",
  "tags": [
    "Solo",
    "School",
    "Custom Engine",
    "3D",
    "Software",
    "C++",
    "PC",
    "Shader"
  ],
  "outLinks": [
    {
      "name": "Github",
      "url": "https://github.com/Abertay-University-SDI/cmp301_coursework-Mummoth-1"
    }
  ],
  "cover": "images/cover.png",
  "additionalAssets": [
    "images/a1.png",
    "images/a2.png",
    "images/a3.png",
    "images/a4.png"
  ],
  "downloadFiles": [
    "files/DX11_Shader.zip"
  ],
  "page": "index.html"
}

=== Piotr-Piwoni/Piotr-Piwoni.github.io/template/project template/metadata.json
{
  "name": "Project Name",
  "short": "A short description of this project.",
  "tags": [
    "Solo",
    "Personal",
    "Unity",
    "3D",
    "Game"
  ],
  "outLinks": [
    {
      "name": "Github",
      "url": "https://github.com/Piotr-Piwoni"
    }
  ],
  "cover": "images/cover.png",
  "additionalAssets": [],
  "downloadFiles": [],
  "page": "index.html"
}

=== Piotr-Piwoni/Piotr-Piwoni.github.io/projects/testProject/metadata.json
{
  "name": "Test Project",
  "short": "A short description of this test project to show on homepage. A short description of this test project to show on homepage.",
  "tags": [
    "Solo",
    "Personal",
    "Unity",
    "3D",
    "Game",
    "Tool",
    "Feature",
    "Software",
    "TypeScript",
    "JavaScript",
    "C#",
    "C++",
    "Python",
    "Java",
    "GDScript",
    "Rust",
    "Lua",
    "Swift",
    "Kotlin",
    "Ruby",
    "Go",
    "Haskell",
    "C",
    "Objective-C",
    "PHP",
    "Dart",
    "Scala",
    "Perl",
    "Dart",
    "Scala",
    "Perl",
    "PHP",
    "Dart",
    "Scala",
    "Perl",
    "Dart",
    "Scala",
    "Perl"
  ],
  "cover": "cover.png",
  "page": "index.html"
}
